# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            The Official Fealty Site
tagline:          
description:      "<b>Plan</b> your strategy.</br>
                   <b>Act</b> through your family.</br>
                   <b>Lead</b> your dynasty.
                   <center></p><a href='/about.html'>Learn more</a></center>"
url:              https://fealtygame.com
baseurl:          
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

excerpt_separator: <!--more-->                  

author:
  name:           FealtyDev
  url:            https://twitter.com/FealtyDev

# disqus
comments:         true

paginate:         5
paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

collections:
  domesday-entries:
    output: true


plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
google_analytics:   UA-138518196-1

gameVersion:        0.1.3

# github:
#  repo:             https://github.com/karloespiritu/blackdoc
